---
title: "FSA NAMs Training Course 3 (Session 3)"
subtitle: "Introductory practical experience in conducting omics-based grouping"
authors: "Michabo Health Science Ltd"
output: html_document
link-citations: true
bibliography: references.bib
date: "2024-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The session focuses on a practical introduction to the calculation and interpretation of bioactivity similarity, with visual outputs. 

The training will use existing code developed by Michabo Health Science Limited, and run within R (and R studio) which should be installed on the trainees local computer.

Working individually or in pairs, attendees will self-pace their progress through the training material and example data provided.


# Cefic MATCHING metabolomics data set 

The tutorial will use data generated as part of the the Cefic MATCHING study.

The aim of the Cefic MATCHING study was to conduct a blinded international ring-trial to investigate whether 6 metabolomics labs, each generating, analysing and reporting metabolomics data from a single exposure study (rodent plasma), generate the same grouping hypothesis [@viant2024demonstrating].

Independent variables:

* Test substances: TS1, TS2, TS3, TS4, TS5, TS7, TS8, TS9
* Sex: Male, Female
* Doses: High, Low

Note that TS6 was excluded prior to exposures.

The data input for the tutorial will of the processed mass spectrometry data derived from the data collected as part from one of the ring-trial labs (Phenome Centre Birmingham).


# Cefic MATCHING metabolomics unblinded!

Decide if we remove this later



