---
title: "Bioactivity-based grouping"
#subtitle: "Introductory practical experience in conducting omics-based grouping"
authors: "Michabo Health Science Ltd"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
link-citations: true
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# t-statistic grouping

The Michabo Health Science workflow chemical grouping uses the control vs condition t-statistics as input. 

```{r read_in_data}
tstats <- read.csv('data/combined_male_tstats.csv', row.names = 1)


```



# Vector normalisation for each condition ('scaling')



```{r read_in_data}
tstats_scaled <- scale(tstats, center=FALSE, scale=TRUE)
```


# t-stat - HCA
```{r HCA}
library(pvclust)
pvclust_res <- pvclust(tstats_scaled, method.hclust = "ward.D2", nboot=1000)


  
plot(pvclust_res, c("si", "au", "bp"), hang=-1)
pp = pvpick(pvclust_res, alpha=0.05, pv="si", type="geq", max.only=TRUE)

```





# References
