---
title: "Supplemental"
#subtitle: "Introductory practical experience in conducting omics-based grouping"
authors: "Michabo Health Science Ltd"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
link-citations: true
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# t-test loop 

Below is a function to run a t-test for all the features for a specific test substance.

```{r root_dir_url, echo=FALSE}
root <- 'https://raw.githubusercontent.com/michabohealthscience/training-fsa/main'
```


```{r t-test_data_one_assay}
library(reshape2)
pqn <- read.csv(file.path(root, 'data/HILIC_POS_male/3_pqn.csv'))
sample_metadata <- read.csv(file.path(root, 'data/HILIC_POS_male/0_sample_metadata_filtered.csv'))

ttest_per_test_substance <- function(pqn, sample_metadata, test_substance=2){
    pqn_t <- data.frame(t(pqn[,-1]))
    colnames(pqn_t) <- pqn$feature_name
    pqn_t$sample_name <- rownames(pqn_t)
  
    pqn_long <- melt(pqn_t, id.vars=c('sample_name'))
    pqn_long <- merge(pqn_long, sample_metadata[,c('sample_name', 'test_substance', 'dose_group')], on='sample_name')
    
    pqn_long <- pqn_long[pqn_long$test_substance != "QC",]
    pqn_long$test_substance <- as.numeric(pqn_long$test_substance)
    pqn_long$dose <- as.numeric(pqn_long$dose)
    pqn_long$value <- as.numeric(pqn_long$value)
    
    # Just check test substance 1
    pqn_long <- pqn_long[pqn_long$test_substance == test_substance | pqn_long$dose_group == 0, ]
    ttest_l = list()
    feature_names <- pqn$feature_name
    doses <- c(1,2)
    
    n = 0
    for (dose in doses){
      
      for (feature in feature_names){
        
        n = n + 1
        
        if (n %% 1000 == 0 || n == 1){
          print(c(n, 'of', length(feature_names)*length(doses)))
        }
        
        treated <- pqn_long[pqn_long$dose_group == dose &
                            pqn_long$variable == feature,]
            
        control <- pqn_long[pqn_long$dose_group == 0 &
                            pqn_long$variable == feature,]
          
        # Specify that we need 3 or more samples in both the treated and control condition
        if (sum(!is.na(treated$value)) > 2 && sum(!is.na(control$value)) > 2){
              ttest_out <- t.test(treated$value, control$value)
              
              if (mean(control$value, na.rm=T) > 0){
                fc <- mean(treated$value, na.rm=T) / mean(control$value, na.rm=T)  
              }else{
                fc <- NA
              }
              
              
              ttest_l[[n]] <- c(feature, dose, ttest_out$p.value, ttest_out$statistic, fc)
        }else{
          ttest_l[[n]] <- c(feature, dose, NA, NA, NA)
        }
            
      }
    }
    ttest_df <- data.frame(Reduce(rbind, ttest_l))
    colnames(ttest_df) <- c('feature_name', 'dose', 'pvalue', 'tstat', 'fc')
    
    ttest_df$pvalue <- as.numeric(ttest_df$pvalue)
    ttest_df$tstat <- as.numeric(ttest_df$tstat)
    ttest_df$fc <- as.numeric(ttest_df$fc)
    
    
    ttest_df <- ttest_df[!is.na(ttest_df$pvalue),]
    rownames(ttest_df) <- NULL
    
    
    return(ttest_df)
}


```

```{r run_function}
ttest_ts2 <- ttest_per_test_substance(pqn, sample_metadata, test_substance=2)
```